controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.2 #0.5
  min_vel_x: -0.1 #0.01 #-0.1

  max_vel_theta: 0.1 #1.5
  min_vel_theta: -0.1

  min_in_place_vel_theta: 0.01
  acc_lim_theta: 3.14 #3.14
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  sim_time: 1.0

  vx_samples: 10.0
  vtheta_samples: 10.0

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.02
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 1
  latch_xy_goal_tolerance: true

  holonomic_robot: false
