my_robot:
    #list of controllers
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 10

    right_wheel_back_hinge_velocity_controller:
      type: effort_controllers/JointVelocityController
      joint: right_wheel_back_hinge
      pid: {p: 100, i: 100, d: 0, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}
      

    left_wheel_back_hinge_velocity_controller:
      type: effort_controllers/JointVelocityController
      joint: left_wheel_back_hinge
      pid: {p: 100, i: 100, d: 0, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}

    right_wheel_hinge_velocity_controller:
      type: effort_controllers/JointVelocityController
      joint: right_wheel_hinge
      pid: {p: 100, i: 100, d: 0, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}
      

    left_wheel_hinge_velocity_controller:
      type: effort_controllers/JointVelocityController
      joint: left_wheel_hinge
      pid: {p: 100, i: 100, d: 0, i_clamp_min: -255.0, i_clamp_max: 255, antiwindup: True}
